# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3077835e93e77a7365f235c7eb3e751cddfd08f6a61138ffae2471ae8d56ec020648012e5a71a88f3629d41fc0ffefd546a97fdf90bc9584120fc7010604a8c7

test:
  secret_key_base: fe0622144aa4ef2064bd455c84589ccb4c52d5a164bf2cfa34a7d594945d6940f8126343f3c893fb3ca3879529770144335570d3a95f0ad645384a7873790282

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
